dist: trusty
sudo: false 
language: clojure
script:
  - echo travis_fold:start:get_deps
  - lein with-profile test:$CLJ_PROFILES:$CLJS_PROFILES deps
  - echo travis_fold:end:get_deps
  - lein with-profile $CLJ_PROFILES test
  - lein with-profile $CLJS_PROFILES test-cljs
matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
      before_install: jdk_switcher use openjdk6 # Needed because travis tries (and fails) to switch to jdk6 before insalling it
      env:
        - CLJ_PROFILES=1.7:1.8:1.9
        - CLJS_PROFILES=1.7:1.8
    - jdk: openjdk7
      env:
        - CLJ_PROFILES=1.7:1.8:1.9
        - CLJS_PROFILES=1.7:1.8
    - jdk: openjdk8
      env:
        - CLJ_PROFILES=1.7:1.8:1.9:1.10
        - CLJS_PROFILES=1.7:1.8:1.9:1.10
    - jdk: openjdk9
      env:
        - CLJ_PROFILES=1.7:1.8:1.9:1.10
        - CLJS_PROFILES=1.7,with-xml:1.8,with-xml:1.9,with-xml:1.10
