dist: trusty
sudo: false 
language: clojure
script:
  - echo travis_fold:start:get_deps
  - lein with-profile $PROFILES deps
  - echo travis_fold:end:get_deps
  - lein with-profile $PROFILES test-all
matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
      before_install: jdk_switcher use openjdk6 # Needed because travis tries (and fails) to switch to jdk6 before insalling it
      env:
        - PROFILES=test:1.8:1.9
    - jdk: openjdk7
      env:
        - PROFILES=test:1.8:1.9
    - jdk: openjdk8
      env:
        - PROFILES=test:1.8:1.9:1.10
